name: Branch Cleanup

on:
  pull_request:
    types: [closed] # Runs when a PR is closed (merged or not)

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true # Ensures action runs only when merged
    runs-on: ubuntu-latest

    steps:
      - name: Delete merged branch using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🗑️ Deleting merged branch: ${{ github.event.pull_request.head.ref }}"
          gh api \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }}
